# Generated by Django 5.1.1 on 2024-09-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FruitFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=150)),
                ('fruit', models.CharField(max_length=150)),
                ('fruit_faq', models.CharField(max_length=500)),
            ],
        ),
    ]
